blank_issues_enabled: false
contact_links:
    - name: Question or Discussion
      url: https://github.com/TrueBurn/twitch-giveaway-bot/discussions
      about: Ask questions and discuss with other community members
